name: 'GitHub Actions Send Daily to Telegram / Feishu'

on:
  push:
    branches: [main]
  schedule:
    - cron: '36 11 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Install node'
        uses: actions/setup-node@v1

      - name: 'Install NPM dependencies'
        run: npm install

      - name: 'Run node'
        run: node index.js

        env:
          SEND_TYPE: ${{ secrets.SEND_TYPE }}
          SIMPREAD_TOKEN: ${{ secrets.SIMPREAD_TOKEN }}
          SIMPREAD_ID: ${{ secrets.SIMPREAD_ID }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
          FEISHU_TOKEN: ${{ secrets.FEISHU_TOKEN }}
